### ISSUE TITLE
Trackman making up metadata

### ISSUE THREAD

**Issue by echarlie** [wuvt/trackman#1]
_From @echarlie on January 9, 2018 22:56_

From bug report recieved at 11:01 EST: "I just queued a track in the to-be-played section, and when I hit the play button to actually play that track, the system logged it as an entirely different track in my playlist (a track that i have neither heard of nor one which was in my queued tracks list).  Pretty weird bug, that.  No idea how to reproduce it."

Trackman was experience some latency issues at the time.

Need to see if there are any issues that could cause this (locking, lookups, etc...)
  

_Copied from original issue: wuvt/wuvt-site#334_

**Comment by mutantmonkey** [comment]
There's unfortunately nothing actionable here, so I'm just going to close this. If we get more information on how to reproduce or additional reports, we can reopen.
