### ISSUE TITLE
Add drag and drop to reorder tracks in the queue

### ISSUE THREAD

**Issue by echarlie** [wuvt/trackman#29]
_From @mutantmonkey on November 20, 2016 1:30_

Currently, there is no way to reorder tracks in the Trackman queue. The best
way to do this is probably to simply add a handle so tracks can be dragged and
dropped to reorder them.

_Copied from original issue: wuvt/wuvt-site#231_

**Comment by echarlie** [comment]
I don't see the utility of this in trackman. it is definitely needed for live-assist.

**Comment by mutantmonkey** [comment]
If nothing else, we can have buttons for this. This was requested by a DJ, so I think we should accommodate this request as I see it as an important feature.

**Comment by echarlie** [comment]
@mutantmonkey this was completed, yes?

**Comment by mutantmonkey** [comment]
Indeed it was. This feature was PR #100 and merged in 7bb567178360eff4da9dca333786f95798d5371f. This can be closed.
