### ISSUE TITLE
Trackman log on/off times should trigger show recordings

### ISSUE THREAD

**Issue by echarlie** [wuvt/trackman#33]
_From @telnoratti on March 2, 2015 5:30_

This is a potential better way to link to shows on the archive.org site.

_Copied from original issue: wuvt/wuvt-site#26_

**Comment by echarlie** [comment]
_From @matthazinski on March 2, 2015 5:38_

So I assume the way this would function is:
- A DJ logs in, which triggers a streamrip to begin
- A DJ logs out, and the streamrip is stopped
- The streamrip is uploaded to IA and linked on the DJ's page. Trackman will need to know which item name is associated with each DJ. (That is, assuming each DJ has one item per show, which is easiest)

Some things to consider are:
- Why is the web server doing the stream rip? Why not have the stream server just provide an API to start/stop arecord? I'm concerned about icecast's buffering issues.
- Why bother passing through the Optimod in the first place? A computer in FM could provide uncompressed audio.

**Comment by echarlie** [comment]
_From @telnoratti on March 2, 2015 5:43_

Trackman itself should not be doing the stream rip, but instead control the process. You're right though it should definitely not be run on the same machine as the webserver. Transcoding could be problematic as my bench-marking of the site's performance hasn't been promising.

There's a nasty edge case where DJs often log out before they're done, so we should keep recording until there's a song change or a new DJ logs in, not sure exactly.

**Comment by echarlie** [comment]
_From @matthazinski on March 4, 2015 6:57_

Another thing: this should also send appropriate metadata (especially DJ name) to the IA as well so it's easier for people to find things. Ideally a playlist would be included too but I'm worried this would make it too attractive a target for DMCAs.

**Comment by echarlie** [comment]
_From @mutantmonkey on March 11, 2015 6:10_

Dude, either it's a copyright violation or it's not. It makes no difference how hard it is to find.

**Comment by echarlie** [comment]
_From @matthazinski on March 11, 2015 18:4_

it's harder for bots to find this way

**Comment by mutantmonkey** [comment]
To be honest, I'm quite partial to the current setup. It has fewer moving parts and has proven itself after several years in production. Does anyone have any thoughts?

**Comment by echarlie** [comment]
Current setup is bulletproof, but does have issues with tracks and DJ talking running over the top of the hour. I'm not sure going to whole-show recordings would be better, though; we need a fallback mechanism to prevent fragility which increases complexity substantially.

Perhaps it would be useful to have a websocket that alerts on arbitrary events, including DJ changing, or support configurable webhooks?

**Comment by mutantmonkey** [comment]
What is the issue exactly? The recordings should be played seamlessly. Also, you realize that with the SSE you can already get the information you're requesting, right?
