### ISSUE TITLE
"Show all DJs" in login shouldn't show automation

### ISSUE THREAD

**Issue by echarlie** [wuvt/trackman#49]

**Comment by mutantmonkey** [comment]
Please explain why.

**Comment by echarlie** [comment]
A user cannot log in as automation, so there's no benefit to displaying it and has the potential to cause confusion.

**Comment by mutantmonkey** [comment]
Okay. The reason I left it is because it's a way to start automation from the "show all DJs" view, but that makes sense I suppose.

**Comment by echarlie** [comment]
being able to start automation from the "show all DJs" view wasn't very intuitive to me; I accidentally did it when trying to log in as automation :)

**Comment by mutantmonkey** [comment]
I fixed this in 77c080f6d052bf597ed512c756138e071874e47a.
