### ISSUE TITLE
"Register New DJ" should have more helpful errors.

### ISSUE THREAD

**Issue by echarlie** [wuvt/trackman#50]
e.g., if you try to register using an existing DJ name, it just says "DJ names must be unique". While true, it should explain "Another DJ already uses this name; please pick a different one" or something like that. 

Perhaps we should offer a way for multiple DJs to share an on-air name (assuming one is inactive or something).

**Comment by mutantmonkey** [comment]
Is it really that unclear what "DJ names must be unique" means? I'm a bit skeptical that someone would be confused by that.

I don't agree about sharing on-air names; I think those should be kept universally unique.

**Comment by echarlie** [comment]
"DJ names must be unique" is an instruction for the field, not a useful error. We've had issues where this has apparently been ambiguous: see the issues we had 2 years ago with the DJ name "Maddie". 

I'd like DJ names to be globally unique, but I can think of enough exceptions where allowing them to be non-unique is okay, or even desirable. Consider "Hickory Dickory Dock", which has been "owned" by multiple DJs over the years; since on-air names *are* show names, I can't search for Hickory Dickory Dock shows from a particular DJ, and while we might want have a one-to-many relationship from air names to DJs, allowing non-unique air names might fill the gap between mandatory sign-in and our current situation.

**Comment by mutantmonkey** [comment]
Eventually DJs and shows will be split, that's just not going to happen in the next release.

**Comment by echarlie** [comment]
I'm willing to close this. It is solved by better end-user documentation or spliting DJs from shows, neither of which is germane to this.
