### ISSUE TITLE
Better Phone number validation when creating or updating DJ

### ISSUE THREAD

**Issue by echarlie** [wuvt/trackman#52]
We should verify that the phone number entered is in fact a phone number, and not a string. We should also ensure it isn't the station's phone number, and maybe sanity check that it's not a 555 number.

**Comment by mutantmonkey** [comment]
I'm not going to bother validating the sanity of the phone number, only the format. If DJs are not going to enter correct information, that's an issue that should be raised with the FMPD, not something we should try to implement a technical solution for.
