### ISSUE TITLE
logging out of admin probably shouldn't redirect back to trackman

### ISSUE THREAD

**Issue by echarlie** [wuvt/trackman#63]
this is a great way to end up with trackman login pages on multiple hosts or multiple people (accidentally) logging---until we have some way to handle multiple active sessions (i.e. prevent them?), I don't think this is a good idea.

Thoughts?

**Comment by mutantmonkey** [comment]
What should happen when you log out then?

**Comment by echarlie** [comment]
can we make a more generic landing page? maybe one that just has 2 links "log into trackman", "log into admin", so that people accessing admin from off our network don't log in > edit something > log out > get prompted to log back in > end up at trackman.

The added benefit is now we have a safe link from the wuvt-site admin interface to send people to.

**Comment by echarlie** [comment]
I would probably make it `/home` or `/signout` or something. Honestly, I'm not sure it matters.

Maybe the solution here is to create different "views" (I'm not sure if they'd be flask views) for the bare `/admin` URL, where users who aren't signed in get a "sign in" link. However, the UX for that isn't *great* for users who are redirected from WUVT-site, since we don't really have SSO

**Comment by mutantmonkey** [comment]
`/signout` doesn't make any sense and `/home` is confusing...

**Comment by mutantmonkey** [comment]
Closing this, as logging out now displays a simple page with a you have been logged out message.
