### ISSUE TITLE
/admin/djs should allow me to expire contact info for a specific DJs

### ISSUE THREAD

**Issue by echarlie** [wuvt/trackman#64]
Some DJs run shows just frequently enough that they're never prompted to update contact info. I'd like to be able to expire some (or all) elements of a DJ's contact info, to force them to update it on their next login.

**Comment by mutantmonkey** [comment]
It does; you can just delete the contact info and they will be prompted to reenter it upon next login. This information is required to log tracks, and we don't really have a concept of "expired" information anyway. There's just a task that runs periodically that clears out this information and marks DJs as inactive.
