### ISSUE TITLE
RFE: Track listeners per track

### ISSUE THREAD

**Issue by echarlie** [wuvt/trackman#96]
Trackman already polls the stream for listeners. We should store this info with each spin of a track, to allow reporting actual total performances rather than aggregate tuning hours to soundexchange, should it become necessary.

https://www.soundexchange.com/service-provider/non-commercial-webcaster/non-commercial-educational-webcaster/

**Comment by mutantmonkey** [comment]
Uh, this happens already, and you can already query it with the API.
Check out the response to https://trackman-fm.apps.wuvt.vt.edu/api/playlists/last15 for an example.
